name: Manual workflow inside the container

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  code-scan:
    runs-on: self-hosted
    container:
      image: hub.softswiss.net/security-pub/pipeguard:feature-nl-appsec-541-github
      options: --user root
      # options: --entrypoint ""
    env:
      CI_JOB_ID: "${{ github.run_id }}-${{ github.run_number }}"
      CI_COMMIT_SHA: "${{ github.sha }}"
      CI_PROJECT_ID: "${{ github.repository_id }}"
      CI_PROJECT_NAME: "${{ github.event.repository.name }}"
      CI_PROJECT_NAMESPACE: "${{ github.repository_owner }}"
      CI_PROJECT_PATH: "${{ github.repository }}"
      CI_PIPELINE_ID: "${{ github.run_id }}"
      CI_PROJECT_DIR: "/project"
      CI_JOB_TOKEN: "${{ secrets.SEC_RULES_TOKEN }}"
      CI_SERVER_HOST: "${{ github.server_url }}"
      CI_COMMIT_REF_NAME: "${{ github.ref_name }}"
      CI_PROJECT_URL: "${{ github.server_url }}/${{ github.repository }}"
      CI_PIPELINE_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      DANGER_GITLAB_API_TOKEN: "TOKENN"
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4 

    - name: code-scan
      run: |
        bash /sec_temp/pipeline/scripts/00_start.sh
        echo "--- Code scan finished"
    