name: Call security pipeline
on:
  workflow_dispatch:
jobs:
  code-scan:
    uses: "stirn/security-pipeline/.github/workflows/include.yaml@main"
    with:
      SEC_RULES_TOKEN: ${{ SEC_RULES_TOKEN }}
