name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string
        
jobs:
  code-scan:
    runs-on: self-hosted
    # container:
    #   image: hub.softswiss.net/security-pub/pipeguard:1.2.3
    #   options: --entrypoint ""

    steps:

    - name: code-scan
      # run: docker run --rm --entrypoint "" hub.softswiss.net/security-pub/pipeguard:1.2.3 semgrep --version
      run: |
          docker run --rm -v ${{ github.workspace }}:/project \
          --platform linux/amd64 \
          -e CI_BUILDS_DIR='none' \
          -e CI_JOB_ID="${{ github.run_id }}-${{ github.run_number }}" \
          -e CI_COMMIT_SHA="${{ github.sha }}" \
          -e CI_PROJECT_ID="${{ github.repository_id }}" \
          -e CI_PROJECT_NAME="${{ github.event.repository.name }}" \
          -e CI_PROJECT_NAMESPACE="${{ github.repository_owner }}" \
          -e CI_PROJECT_PATH="${{ github.repository }}" \
          -e CI_PIPELINE_ID="${{ github.run_id }}" \
          -e CI_PROJECT_DIR='/project' \
          -e CI_JOB_TOKEN="${{ secrets.SEC_RULES_TOKEN }}" \
          -e CI_SERVER_HOST="${{ github.server_url }}" \
          -e CI_COMMIT_REF_NAME="${{ github.ref_name }}" \
          -e CI_PROJECT_URL="${{ github.server_url }}/${{ github.repository }}" \
          -e CI_PIPELINE_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          -e DANGER_GITLAB_API_TOKEN='TOKENN' \
          hub.softswiss.net/security-pub/pipeguard:feature-nl-appsec-541-github
    
    # - name: Show Semgrep version running inside container
    #   run: semgrep --version
